package objectRepository;

import org.openqa.selenium.By;

public class BasketOR {
    public static final By SEPET_SIPARISI_TAMAMLA_BUTTON_MWEB = By.id("v2-checkout-apply-items");
    public static final By SEPET_URUN_EKSI_ICON_1_MWEB = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div.cc-quantity-and-price > div > div > a.quantity-increase > svg");
    public static final By SEPET_URUN_EKSI_ICON_DESING_1_MWEB = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div.cc-quantity-and-price > div > div > a.quantity-increase > svg > path");
    public static final By SEPET_URUN_EKSI_ICON_1_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div > div > div > a.quantity-increase > svg");
    public static final By SEPET_URUN_EKSI_ICON_DESING_1_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div > div > div > a.quantity-increase > svg > path");
    public static final By SEPET_URUN_ARTI_ICON_1_MWEB = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div.cc-quantity-and-price > div > div > a.quantity-decrease > svg");
    public static final By SEPET_URUN_ARTI_ICON_DESING_1_MWEB = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div.cc-quantity-and-price > div > div > a.quantity-decrease > svg > path");
    public static final By SEPET_URUN_ARTI_ICON_1_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div > div > div > a.quantity-decrease > svg");
    public static final By SEPET_URUN_ARTI_ICON_DESING_1_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div > div > div > a.quantity-decrease > svg > path");
    public static final By SEPET_URUN_DELETE_ICON_1_MWEB = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div.cc-quantity-and-price > div > div > a.product-delete.removefromcart-link > svg");
    public static final By SEPET_URUN_DELETE_ICON_DESIGN_1_MWEB = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div.cc-quantity-and-price > div > div > a.product-delete.removefromcart-link > svg > path");
    public static final By SEPET_URUN_DELETE_ICON_1_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div > div > div > a.product-delete.removefromcart-link > svg");
    public static final By SEPET_URUN_DELETE_ICON_DESIGN_1_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div > div > div > a.product-delete.removefromcart-link > svg > path");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_1_WEB = By.xpath("//*[@id=\"FancyGiftSelect\"]/div[2]/div/div/div/div/div/ul/li[1]");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_1_MWEB = By.xpath("/html[1]/body[1]/div[2]/div[4]/div[2]/div[1]/div[1]/input[1]");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_2_MWEB = By.xpath("/html[1]/body[1]/div[2]/div[4]/div[2]/div[1]/div[2]/input[1]");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_2_WEB = By.xpath("//*[@id=\"FancyGiftSelect\"]/div[2]/div/div/div/div/div/ul/li[2]");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_3_MWEB = By.xpath("/html[1]/body[1]/div[2]/div[4]/div[2]/div[1]/div[3]/input[1]");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_3_WEB = By.xpath("//*[@id=\"FancyGiftSelect\"]/div[2]/div/div/div/div/div/ul/li[3]");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_1_MWEB_SUPP = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/div[1]/input");
    public static final By SEPET_SONRASI_HEDIYE_SECIM_PAGE_HEDIYE_2_MWEB_SUPP = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/div[2]/input");
    public static final By ADRES_EKLE_PAGE_BU_ADRESI_KULLAN_BUTTON = By.xpath("//a[@id='useAddressButton']");
    public static final By ADRES_EKLE_PAGE_BU_ADRESI_KULLAN_BUTTON_WEB = By.id("setAddressButton_checkout_add");
    public static final By ADRES_EKLE_PAGE_CEP_TELEFONU_TEXTBOX = By.xpath("//input[@id='Address_MobilePhoneNumber']");
    public static final By ADRES_EKLE_PAGE_KAYDET_BUTTON = By.xpath("//input[@id='addaddress']");
    public static final By ADRES_PAGE_DEVAM_ET_BUTTON = By.xpath("//input[@id='ContinueOrderButton']");
    public static final By SEPET_FIRST_PRODUCT_COUNT_MWEB = By.xpath("/html/body/div[2]/div[4]/div[1]/div[3]/form/div[1]/div[1]/div[2]/div[2]/div/div/div/span");
    public static final By SEPET_FIRST_PRODUCT_COUNT_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div.cc-div > div.right > div.cc-right > div > div > div > span");
    public static final By SEPET_FIRST_PRODUCT_NAME_MWEB = By.xpath("//body/div[2]/div[4]/div[1]/div[3]/form/div[1]/div[1]/div[2]/div[1]/a");
    public static final By SEPET_FIRST_PRODUCT_NAME_MWEB_FITMODA = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-head > a");
    public static final By SEPET_PROGRESS_BAR = By.xpath("//div[@class='cart-progress-bar']");
    public static final By SEPET_PROGRESS_BAR_WEB = By.xpath("//div[@class='checkout-progress-v2']");
    public static final By SEPET_PROGRESS_BAR_AKTIF_TAB = By.xpath("//span[@class='cart-progress-bar-label cart-progress-bar-label-active']");
    public static final By SEPET_PROGRESS_BAR_AKTIF_TAB_WEB = By.xpath("//a[@class='selected']");
    public static final By SEPET_PROGRESS_BAR_AKTIF_NUMBER=By.xpath("//span[@class='cart-progress-bar-number-active']");
    public static final By SEPET_PROGRESS_BAR_NUMBER_1=By.xpath("//span[normalize-space()='1']");
    public static final By SEPET_PROGRESS_BAR_NUMBER_2=By.xpath("//span[normalize-space()='2']");
    public static final By SEPET_PROGRESS_BAR_NUMBER_3=By.xpath("//span[normalize-space()='3']");
    public static final By NEW_SEPET_FIYAT_TYPE = By.xpath("//*[@id=\"cartWrapper\"]/div[3]/form/div[1]/div[1]/div[2]/div[2]/div[2]/span");
    public static final By SEPET_FIYAT_TYPE = By.cssSelector("#cartWrapper > div.cart > form > div.cart-content.mmo > div:nth-child(1) > div.right > div.cc-right > div.cc-quantity-and-price > span");
    public static final By SEPET_FIYAT_TYPE_WEB = By.xpath("//span[@class='productPrice']");
    public static final By ADRES_PAGE_TESLIMAT_ADRESI_WRAPPER = By.xpath("//div[@class='summary-deliver-wrapper deliver-address summary-currently-supp-deliver-wrapper']");
    public static final By ADRES_PAGE_TESLIMAT_ADRESI_WRAPPER_WEB = By.xpath("//div[@class='address-select shipping-address-wrapper']");
    public static final By ADRES_PAGE_TESLIMAT_ADRESI_WRAPPER_VITAMINLER = By.xpath("//div[@class='summary-deliver-wrapper deliver-address summary-currently-supp-deliver-wrapper summary-currently-vit-deliver-wrapper']");
    public static final By ADRES_PAGE_TESLIMAT_ADRESI_WRAPPER_FITMODA = By.xpath("//div[@id='useSameAddressForBilling-wrapper-elem']");
    public static final By ADRES_PAGE_FATURA_ADRESI_WRAPPER = By.xpath("//div[@class='summary-deliver-wrapper invoice-address summary-currently-supp-deliver-wrapper']");
    public static final By ADRES_PAGE_FATURA_ADRESI_WRAPPER_WEB = By.xpath("//div[@class='address-select billing-address-wrapper']");
    public static final By ADRES_PAGE_FATURA_ADRESI_WRAPPER_VITAMINLER = By.xpath("//div[@class='summary-deliver-wrapper invoice-address summary-currently-supp-deliver-wrapper summary-currently-vit-deliver-wrapper']");
    public static final By ADRES_PAGE_FATURA_ADRESI_WRAPPER_FITMODA = By.xpath("//div[@class='summary-deliver-wrapper deliver-address summary-currently-supp-deliver-wrapper summary-currently-fit-deliver-wrapper']");
    public static final By ADRES_PAGE_FATURAM_SIPARIS_ILE_BIRLIKTE_GONDERILSIN_WRAPPER = By.id("useSameAddressForBilling-wrapper-elem");
    public static final By ADRES_PAGE_FATURAM_SIPARIS_ILE_BIRLIKTE_GONDERILSIN_WRAPPER_WEB = By.xpath("//input[@id='useSameAddressForBilling']");
    public static final By SEPET_ADRES_FATURAM_SIPARISLE_GONDERILSIN_CHECKBOX = By.id("useSameAddressForBilling");
    public static final By ADRES_PAGE_FATURA_ADRESI_HIDDEN = By.xpath("//div[@class='faturaAdresi hidden billingTd']");
    public static final By ADRES_PAGE_FATURA_ADRESI_HIDDEN_WEB = By.xpath("//div[@class='address-select billing-address-wrapper']");
    public static final By ADRES_PAGE_YENI_ADRES_EKLE_BUTTON_MWEB = By.xpath("//a[@class='btn-add-address summary-new-address-add']");
    public static final By ADRES_PAGE_YENI_ADRES_EKLE_BUTTON_WEB = By.xpath("//a[@class='add-new-address']");
    public static final By ADRES_EKLE_PAGE_ADRES_SECIMINE_GERI_DON_BUTTON = By.id("back-to-address-chosen-page");
    public static final By ADRES_EKLE_PAGE_ADRES_SECIMINE_GERI_DON_BUTTON_WEB = By.xpath("//a[@title='Kapat']");
    public static final By ADRES_PAGE_TESLIMAT_SECIMI_TEXT_WEB = By.xpath("//h1[normalize-space()='Teslimat Seçenekleri']");
    public static final By ADRES_PAGE_FATURAM_SIPARI_ILE_BIRLIKTE_GONDERILSIN_TEXT_WEB = By.id("sameAdressCheckboxContainer");
    public static final By ADRES_PAGE_FATURA_ADRES_DUZENLE_BUTTON = By.id("EditBillingAddress");
    public static final By ADRES_PAGE_TESLIMAT_ADRES_DUZENLE_BUTTON = By.id("EditShippingAddress");
    public static final By ADRES_PAGE_FATURA_ADRES_DUZENLE_BUTTON_WEB = By.id("AddressEditButtonBilling");
    public static final By ADRES_PAGE_TESLIMAT_ADRES_DUZENLE_BUTTON_WEB = By.id("AddressEditButtonShipping");
    public static final By ADRES_PAGE_TESLIMAT_SECIMI_TEXT = By.id("cargoSelectionText");
    public static final By ADRES_PAGE_TESLIMAT_ADRES_BASLIK=By.id("summary-deliver-address-title");
    public static final By ADRES_PAGE_FATURA_ADRES_BASLIK=By.id("summary-invoice-address-title");
    public static final By ADRES_PAGE_FATURA_ADRES_SECIM=By.id("billAddressSelectControl");
    public static final By ADRES_PAGE_FATURA_ADRES_SECIM_1=By.xpath("//*[@id=\"billAddressSelectControl\"]/option[1]");
    public static final By ADRES_PAGE_FATURA_ADRES_SECIM_2=By.xpath("//*[@id=\"billAddressSelectControl\"]/option[2]");
    public static final By ADRES_PAGE_KARGO_SECENEGI_SIZE = By.xpath("(//div[@class='li-container'])");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_SECIM_1 = By.xpath("(//div[@class='li-container'])[1]");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_SECIM_2 = By.xpath("(//div[@class='li-container'])[2]");
    public static final By ADRES_PAGE_ADRESINE_HEMEN_TESLIM_WRAPPER_HIDDEN = By.xpath("//div[@class='shipping-column sameday-delivery']");
    //public static final By ADRES_PAGE_ADRESINE_HEMEN_TESLIM_WRAPPER_HIDDEN_WEB = By.xpath("//div[@class='shipping-column sameday-delivery']");
    public static final By ADRES_PAGE_ADRESINE_HEMEN_TESLIM_WRAPPER_OPEN = By.xpath("//div[@class='shipping-column sameday-delivery active']");
    public static final By HEMEN_TESLIM_TEXT = By.xpath("//div[@class='shipping-column sameday-delivery']");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_WRAPPER = By.xpath("//div[@class='shipping-head ']");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_WRAPPER_WEB = By.xpath("(//div[@class='shipping-head'])[2]");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_WRAPPER_FITMODA = By.xpath("//div[@class='shipping-head fitmoda-standard-shipping']");
    public static final By SEPET_NOTU_CONTAINER = By.xpath("//div[@class='hidden giftnotetextcontainer controls']");
    public static final By ADRES_PAGE_FATURAM_SIPARIS_ILE_BIRLIKTE_GONDERILSIN_TEXT = By.xpath("//label[@for='useSameAddressForBilling']");
    public static final By ADRES_PAGE_SEPET_NOTU_EKLEMEK_ISTIYORUM_TEXT_MWEB = By.xpath("//span[contains(text(),'Sipariş notu eklemek istiyorum')]");
    public static final By ADRES_PAGE_SEPET_NOTU_EKLEMEK_ISTIYORUM_TEXT_WEB = By.id("giftnotetext");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_SECIM_1_AKTIFLIK_DURUM=By.xpath("/html/body/div[2]/div[4]/div[3]/div[5]/div[2]/div/div[2]/ul/li[1]");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_SECIM_2_AKTIFLIK_DURUM=By.xpath("/html/body/div[2]/div[4]/div[3]/div[5]/div[2]/div/div[2]/ul/li[2]");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_SECIM_1_AKTIFLIK_DURUM_FITMODA=By.xpath("/html/body/div[2]/div[3]/div[3]/div[5]/div[2]/div/div[2]/ul/li[1]");
    public static final By ADRES_PAGE_STANDART_TESLIMAT_SECIM_2_AKTIFLIK_DURUM_FITMODA=By.xpath("/html/body/div[2]/div[3]/div[3]/div[5]/div[2]/div/div[2]/ul/li[2]");
    public static final By ODEME_PAGE_ODEME_SECENEKLERI_SIZE = By.xpath("(//div[@class='btn-payment-type-dropdown-icon-wrapper'])");
    public static final By ODEME_PAGE_ODEME_SECENEKLERI_SIZE_WEB = By.xpath("(//div[@class='payment-method'])");
    public static final By ODEME_PAGE_KREDI_KARTI_SECENEK = By.xpath("//a[@name='Payments.Inveon']//div[@class='btn-payment-type-text-wrapper']");
    public static final By ODEME_PAGE_KREDI_KARTI_SECENEK_WRAPPER_WEB = By.xpath("//label[@data-name='Kredi Kartı']");
    public static final By ODEME_PAGE_KREDI_KARTI_SECENEK_WEB = By.xpath("(//div[@class='payment-method'])[1]");
    public static final By ODEME_PAGE_KREDI_KARTI_SECENEK_BUTTON = By.xpath("//a[@name='Payments.Inveon']");
    public static final By ODEME_PAGE_HAVALE_SECENEK = By.xpath("//a[@name='Payments.MoneyTransfer']//div[@class='btn-payment-type-text-wrapper']");
    public static final By ODEME_PAGE_HAVALE_SECENEK_BUTTON = By.xpath("//a[@name='Payments.MoneyTransfer']");
    public static final By ODEME_PAGE_KAPIDA_KREDI_KARTI_SECENEK = By.xpath("//a[@name='Payments.CreditCardOnDelivery']//div[@class='btn-payment-type-text-wrapper']");
    public static final By ODEME_PAGE_KAPIDA_KREDI_KARTI_SECENEK_BUTTON = By.xpath("//a[@name='Payments.CreditCardOnDelivery']");
    public static final By ODEME_PAGE_KAPIDA_NAKIT_SECENEK = By.xpath("//a[@name='Payments.CashOnDelivery']//div[@class='btn-payment-type-text-wrapper']");
    public static final By ODEME_PAGE_KAPIDA_NAKIT_SECENEK_BUTTON = By.xpath("//a[@name='Payments.CashOnDelivery']");
    public static final By ODEME_PAGE_ALISVERIS_KREDISI_SECENEK = By.xpath("//a[@name='Payments.Compay']//div[@class='btn-payment-type-text-wrapper']");
    public static final By ODEME_PAGE_ALISVERIS_KREDISI_SECENEK_BUTTON = By.xpath("//a[@name='Payments.Compay']");
    public static final By ODEME_PAGE_KREDI_KARTI_EKSIK_ALANLAR_HATA_MESAJI = By.id("errorSummaryList");
    public static final By ODEME_PAGE_KAYITLI_KARTLARIM_BUTTON_WEB = By.id("savedCardBtn");
    public static final By ODEME_PAGE_KAYITLI_KARTINIZ_YOK_TEXT_WEB = By.xpath("//p[contains(text(),'bulunmamaktadır.')]");
    public static final By ODEME_PAGE_YENI_KART_EKLE_BUTTON_WEB = By.id("newCardBtn");
    public static final By ODEME_PAGE_KREDI_KART_AD_SOYAD_TEXTBOX = By.id("CardholderName");
    public static final By ODEME_PAGE_KREDI_KART_NO_TEXTBOX = By.id("CardNumber");
    public static final By ODEME_PAGE_KREDI_KART_AY_DROPDOWN = By.id("ExpireMonth");
    public static final By ODEME_PAGE_KREDI_KART_YIL_DROPDOWN = By.id("ExpireYear");
    public static final By ODEME_PAGE_KREDI_KART_CVV_TEXTBOX = By.id("CardCode");
    public static final By ODEME_PAGE_SOZLESME_POPUP_KAPAT_ICON = By.xpath("//a[@title='Close']");
    public static final By ODEME_PAGE_SOZLESME_POPUP_KAPAT_ICON_WEB = By.xpath("//a[@title='Kapat']");
    public static final By ODEME_PAGE_KREDI_KARTI_TEK_TEKIM_TUTAR_1 = By.xpath("/html[1]/body[1]/div[2]/div[4]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/ul[1]/li[1]/div[1]/div[4]");
    public static final By ODEME_PAGE_KREDI_KARTI_TEK_TEKIM_TUTAR_1_WEB = By.xpath("//*[@id=\"installment-table-content-div\"]/div[2]/label/span[3]");
    public static final By ODEME_PAGE_KREDI_KARTI_TEK_TEKIM_TUTAR_1_FITMODA = By.xpath("/html[1]/body[1]/div[2]/div[3]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/ul[1]/li[1]/div[1]/div[4]");
    public static final By ODEME_PAGE_KREDI_KARTI_TEK_TEKIM_TUTAR_2_FITMODA = By.xpath("/html[1]/body[1]/div[2]/div[3]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/ul[1]/li[1]/div[1]/div[5]");
    public static final By ODEME_PAGE_KREDI_KARTI_TEK_TEKIM_TUTAR_2 = By.xpath("/html[1]/body[1]/div[2]/div[4]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/ul[1]/li[1]/div[1]/div[5]");
    public static final By ODEME_PAGE_SATIS_FORM_FIELD = By.xpath("//div[@class='perm-row-check']");
    public static final By ODEME_PAGE_KREDI_KARTI_TAKSIT_SECENEKLERI_TEXT = By.xpath("//div[@class='installment-heading']");
    public static final By ODEME_PAGE_KREDI_KARTI_TAKSIT_SECENEKLERI_FIELD = By.xpath("//div[@class='installment-options']");
    public static final By ODEME_PAGE_KREDI_KARTI_TAKSIT_SECENEKLERI_ACTIVE_TAKSIT = By.xpath("//li[@class='active']");
    public static final By ODEME_PAGE_KREDI_KARTI_TAKSIT_SECENEKLERI_ACTIVE_TAKSIT_WEB = By.xpath("//div[@class='installment-table hire-purchase-select-radio active']");
    public static final By ODEME_PAGE_ONBILGILENDIRME_FORMU = By.xpath("//a[@id='onbilgilendirmeFormu']");
    public static final By ODEME_PAGE_ONBILGILENDIRME_FORMU_WEB = By.id("onbilgilendirmeFormuUrl");
    public static final By ODEME_PAGE_MESAFELISATIS_SOZLESMESI = By.xpath("//a[@id='mesafeliSatisSozlesmesi']");
    public static final By ODEME_PAGE_MESAFELISATIS_SOZLESMESI_WEB = By.id("mesafeliSatisSozlesmesiUrl");
    public static final By ODEME_PAGE_FORM_IFRAME=By.className("fancybox-iframe");
    public static final By ODEME_PAGE_ONBILGILENDIRME_FORMU_BASLIK=By.xpath("//strong[contains(text(),'ÖN BİLGİLENDİRME FORMU')]");
    public static final By ODEME_PAGE_MESAFELISATIS_SOZLESMESI_BASLIK=By.xpath("//strong[contains(text(),'MESAFELİ SATIŞ SÖZLEŞMESİ')]");
    public static final By ODEME_PAGE_KART_EKLE_TEXT = By.xpath("//h4[normalize-space()='Kart Ekle']");
    public static final By ODEME_PAGE_KAYITLI_KARTINIZ_YOK_TEXT = By.cssSelector("body > div:nth-child(6) > div:nth-child(5) > div:nth-child(4) > form:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)");
    public static final By ODEME_PAGE_KAYITLI_KARTINIZ_YOK_TEXT_FITMODA = By.cssSelector("body > div:nth-child(6) > div:nth-child(4) > div:nth-child(5) > form:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)");
    public static final By ODEME_PAGE_KART_UZERINDEKI_ISIM_SOYISIM_TEXT = By.xpath("//label[contains(text(),'Kart Üzerindeki İsim Soyisim')]");
    public static final By ODEME_PAGE_KART_UZERINDEKI_ISIM_SOYISIM_TEXT_WEB = By.xpath("//label[@for='CardholderName']");
    public static final By ODEME_PAGE_KART_NUMARASI_TEXT = By.xpath("//label[contains(text(),'Kart Numarası')]");
    public static final By ODEME_PAGE_KART_NUMARASI_TEXT_WEB = By.xpath("//label[@for='CardNumber']");
    public static final By ODEME_PAGE_KART_SON_KULLANMA_TARIHI_TEXT = By.xpath("//label[normalize-space()='Son Kullanma Tarihi']");
    public static final By ODEME_PAGE_KART_SON_KULLANMA_TARIHI_TEXT_WEB = By.xpath("//label[@for='ExpireMonth']");
    public static final By ODEME_PAGE_KART_GUVENLIK_KODU_TEXT = By.xpath("//label[normalize-space()='Güvenlik Kodu (CVV)']");
    public static final By ODEME_PAGE_KART_GUVENLIK_KODU_TEXT_WEB = By.xpath("//label[@for='CardCode']");
    public static final By ODEME_PAGE_KART_TAKSIT_SECENEKLERI_KART_BILGILERINI_GIRDIKTEN_TEXT = By.xpath("//div[@id='installmentInfoBox']");
    public static final By ODEME_PAGE_KART_KAYITLI_KARTINIZ_BULUNMAMAKTADIR_TEXT = By.xpath("//*[@id=\"PaymentForm\"]/div[1]/div[1]/div/div/div[1]/div[1]");
    public static final By ODEME_PAGE_KART_KREDI_KARTI_KAYDETMEK_ISTIYORUM_TEXT = By.xpath("//div[@id='socc']//div[@class='perm-row-label']");
    public static final By ODEME_PAGE_KART_SECURE_3D_ILE_ODEMEK_ISTIYORUM_TEXT = By.xpath("//div[@class='perm-row flx-align-center']//div[@class='perm-row-label']");
    public static final By ODEME_PAGE_HAVALE_ONCE_BANKA_SECINIZ_UYARI = By.xpath("//div[@class='info-box no-icon info-box-moneytransfer']");
    public static final By ODEME_PAGE_HAVALE_YAPILACAK_BANKA_TEXT = By.xpath("//div[@class='moneytransfer-titletext']");
    public static final By ODEME_PAGE_HAVALE_DIKKAT_EDILMESI_GEREKENLER_TEXT = By.xpath("//div[@class='info-box-reduced-brightness']");
    public static final By ODEME_PAGE_HAVALE_BANKA_LOGO = By.xpath("/html/body/div[2]/div[4]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[1]/div[1]/img[1]");
    public static final By ODEME_PAGE_HAVALE_BANKA_LOGO_FITMODA = By.xpath("/html/body/div[2]/div[3]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[1]/div[1]/img[1]");
    public static final By ODEME_PAGE_HAVALE_BANKA_LIST_SIZE = By.xpath("//*[@id=\"moneytransfer_container_pay\"]/div/div[4]/table[2]/tbody/tr");
    public static final By ODEME_PAGE_HAVALE_HESAP_ADI_TEXT = By.xpath("//small[contains(text(),'Hesap Adı:')]");
    public static final By ODEME_PAGE_HAVALE_IBAN = By.xpath("/html/body/div[2]/div[4]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[1]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_IBAN_FITMODA = By.xpath("/html/body/div[2]/div[3]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[1]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_HESAP_ADI = By.xpath("/html/body/div[2]/div[4]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[1]/div[2]/strong");
    public static final By ODEME_PAGE_HAVALE_HESAP_ADI_FITMODA = By.xpath("/html/body/div[2]/div[3]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[1]/div[2]/strong");
    public static final By ODEME_PAGE_HAVALE_HESAP_NO = By.xpath("/html/body/div[2]/div[4]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[2]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_HESAP_NO_FITMODA = By.xpath("/html/body/div[2]/div[3]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[2]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_SUBE_ADI = By.xpath("/html/body/div[2]/div[4]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[3]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_SUBE_ADI_FITMODA = By.xpath("/html/body/div[2]/div[3]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[3]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_SUBE_KODU = By.xpath("/html/body/div[2]/div[4]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[4]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_SUBE_KODU_FITMODA = By.xpath("/html/body/div[2]/div[3]/div[1]/form/div[1]/div[2]/div[1]/div/div[1]/div/div[5]/div[2]/table/tbody/tr[4]/td[2]/span");
    public static final By ODEME_PAGE_HAVALE_IBAN_TEXT = By.xpath("(//small[contains(text(),'IBAN:')])[1]");
    public static final By ODEME_PAGE_HAVALE_HESAP_NO_TEXT = By.xpath("(//small[contains(text(),'Hesap No:')])[1]");
    public static final By ODEME_PAGE_HAVALE_SUBE_ADI_TEXT = By.xpath("(//small[contains(text(),'Şube Adı:')])[1]");
    public static final By ODEME_PAGE_HAVALE_SUBE_KODU_TEXT = By.xpath("(//small[contains(text(),'Şube Kodu:')])[1]");
    public static final By ODEME_PAGE_KAPIDA_KREDI_KARTI_METIN = By.id("creditcardondelivery_container");
    public static final By ODEME_PAGE_KAPIDA_NAKIT_METIN = By.id("cashondelivery_container");
    public static final By SEPETIM_PROGRESS_BAR=By.xpath("//span[normalize-space()='Sepetim']");
    public static final By SEPET_STOK_UYARI_MESAJI_MWEB=By.xpath("//div[@class='message-error alert alert-error']");
    public static final By ODEME_PAGE_ALISVERIS_KREDISI_IMAGE=By.xpath("//img[contains(@class,'shopping-loan-logo')]");
    public static final By SEPET_SIPARIS_OZETI_FIELD=By.xpath("//div[@class='summary']");
    public static final By SEPET_SIPARIS_OZETI_FIELD_WEB =By.xpath("//div[@class='order-sum']");
    public static final By PROGRESS_BAR_SEPETIM=By.xpath("//span[normalize-space()='Sepetim']");
    public static final By PROGRESS_BAR_ADRES=By.xpath("//span[normalize-space()='Adres']");
    public static final By PROGRESS_BAR_ODEME=By.xpath("//span[normalize-space()='Ödeme']");
    public static final By ADRES_PAGE_AGT_TESLIMAT_AKTIF_1=By.xpath("//ul[@class='sameday-delivery-list']/li[not(@class='disabled-slot')][1]");
    public static final By ADRES_PAGE_AGT_TESLIMAT_INFO_MESSAGE=By.xpath("//div[@class='ui-tooltip-content']");
    public static final By ALISVERIS_KREDISI_TEST_BANK=By.xpath("//h1[normalize-space()='Compay Bank']");
    public static final By SEPET_TOPLAM_TUTAR_WEB = By.cssSelector("body > div.in_container > div > form > div > div.ciw-right > div.order-sum > ul > li:nth-child(3) > div:nth-child(2)");
    public static final By SEPET_TOPLAM_TUTAR_WEB_FITMODA = By.xpath("/html/body/div[7]/div[3]/form/div/div[2]/div[1]/ul/li[3]/div[2]");
    public static final By SEPET_INDIRIM_TUTAR_WEB_FITMODA = By.cssSelector("body > div.in_container > div.container.fitmoda-checkout-bottom > form > div > div.ciw-right > div.order-sum > ul > li:nth-child(3) > div.cart-discount");
    public static final By SEPET_INDIRIM_TUTAR_WEB = By.cssSelector("body > div.in_container > div > form > div > div.ciw-right > div.order-sum > ul > li:nth-child(3) > div.cart-discount");
    public static final By SEPET_HAVALE_INDIRIM_TUTAR_WEB_FITMODA = By.cssSelector("");
    public static final By SEPET_ARA_TOPLAM_TUTAR_WEB_FITMODA = By.cssSelector("body > div.in_container > div.container.fitmoda-checkout-bottom > form > div > div.ciw-right > div.order-sum > ul > li:nth-child(1) > div:nth-child(2)");
    public static final By SEPET_ARA_TOPLAM_TUTAR_WEB = By.cssSelector("body > div.in_container > div > form > div > div.ciw-right > div.order-sum > ul > li:nth-child(1) > div:nth-child(2)");
    public static final By SEPET_HAVALE_INDIRIM_TUTAR_WEB = By.cssSelector("body > div.in_container > div > form > div > div.ciw-right > div.order-sum > ul > li:nth-child(4) > div:nth-child(2)");
    public static final By SEPET_KUPON_KODU_CHECKBOX = By.cssSelector(".coupon-code-check");
    public static final By SEPET_KUPON_KODU_SIL_BUTTON = By.xpath("//*[@id=\"removediscountcouponcode\"]");
    public static final By SEPET_KUPON_KODU_ACTIVE = By.cssSelector(".coupon-code-check.active");
    public static final By SEPET_KUPON_KODU_CHECKBOX_MWEB = By.cssSelector(".coupon-code-check");
    public static final By SEPET_KUPON_KODU_TEXTBOX = By.id("discountcouponcode");
    public static final By SEPET_INDIRIMI_KULLAN_BUTTON = By.id("applydiscountcouponcode");
    public static final By SEPET_HATA_MESAJI = By.cssSelector("div[class='module-content'] div[class='message-error alert alert-error']");
    public static final By SEPET_HATA_MESAJI_MWEB = By.cssSelector("div[class='module-content'] div[class='message-error alert alert-error']");
    public static final By SEPET_URUN_DELETE_ICON_1_WEB = By.xpath("(//a[@data-label='RemoveCartItem'])[1]");
    public static final By SEPET_URUN_DELETE_ICON_1_MWEB_V1 = By.xpath("(//a[@data-label='RemoveCartItem'])[1]");
    public static final By SEPET_URUN_EKSI_ICON_1_WEB_FITMODA = By.xpath("/html/body/div[7]/div[3]/form/div/div[1]/div[2]/div[2]/div[3]/span/a[2]");
    public static final By SEPET_URUN_ADET_INPUT_1_WEB_FITMODA = By.xpath("/html/body/div[7]/div[3]/form/div/div[1]/div[2]/div[2]/div[3]/span/input");
    public static final By SEPET_URUN_DELETE_ICON_SIZE = By.xpath("(//div[@class='cart-product-remove'])");
    public static final By SEPET_URUN_DELETE_ICON_SIZE_MWEB = By.xpath("(//a[@data-label='RemoveCartItem'][normalize-space()='Ürünü Sil'])");
    public static final By SEPET_URUNU_SIL_BUTTON_POPUP = By.id("delete-cart-product");
    public static final By SEPET_URUNU_SIL_BUTTON_POPUP_FITMODA = By.xpath("(//a[normalize-space()='Ürünü Sil'])[1]");
    public static final By SEPET_SEPETI_ONAYLA_BUTTON_GUEST = By.id("checkoutContinue");
    public static final By SEPET_SEPETI_ONAYLA_BUTTON = By.id("checkout");

    public static final By SEPET_SATIN_AL_BUTTON = By.xpath("//input[@id='checkoutContinue']");
    public static final By SEPET_SIPARISI_TAMAMLA_BUTTON_MWEB_V2 = By.id("v2-checkout-apply-items");
    public static final By SEPET_SIPARISI_TAMAMLA_BUTTON_WEB = By.id("checkout");
    public static final By ODEME_SIPARISI_TAMAMLA_BUTTON_WEB = By.id("nextstep");
    public static final By ODEME_PAGE_SATIS_FORM_CHECKBOX_WEB = By.xpath("//i[@class='sozlesme-check']");
    public static final By SEPET_SEPETI_ONAYLA_BUTTON_WEB_ID_GUEST = By.xpath("checkoutContinue");
    public static final By SEPET_TOPLAM_TUTAR_FIELD_MWEB_V2 = By.xpath("//div[@class='total-amount']");
    public static final By SEPET_TOPLAM_TUTAR_FIELD_WEB = By.xpath("//div[@class='order-sum']");
    public static final By SEPET_SATIN_AL_BUTTON_WEB_ID = By.id("checkout");
    public static final By SEPET_URUN_ADETI_WEB = By.xpath("/html/body/div[9]/div/form/div/div[1]/div[2]/div[2]/div[3]/span/input");
    public static final By SEPET_TOPLAM_TEXT = By.xpath("//span[@class='title']");
    public static final By SEPET_TOPLAM_TEXT_WEB = By.xpath("//div[normalize-space()='TOPLAM']");
    public static final By SEPET_TOPLAM_TUTAR_MWEB_V2 = By.cssSelector("#v2-checkout > div.cot-container > div.total-row.no-bottom-border-row.total-amount-container > div.total-amount > span:nth-child(2)");
 //   public static final By SEPET_TOPLAM_TUTAR_WEB = By.xpath("/html/body/div[9]/div/form/div/div[2]/div[1]/ul/li[3]/div[2]");
    public static final By SEPET_ARA_TOPLAM_TEXT = By.xpath("//div[normalize-space()='Ara Toplam']");
    public static final By SEPET_ARA_TOPLAM_TEXT_WEB = By.xpath("//div[normalize-space()='ARA TOPLAM']");
    public static final By SEPET_KARGO_TEXT = By.xpath("//div[normalize-space()='Kargo']");
    public static final By SEPET_KARGO_TEXT_WEB = By.xpath("//div[normalize-space()='KARGO']");
    public static final By SEPET_ARA_TOPLAM_TUTAR_MWEB_V2 = By.xpath("//div[@class='sub-total']");
    public static final By SEPET_ARA_TOPLAM_TUTAR_TEXT_WEB = By.xpath("//div[normalize-space()='ARA TOPLAM']");
    public static final By SEPET_KARGO_BILGI = By.xpath("//div[@class='shipping-description']");
    public static final By SEPET_KARGO_BILGI_WEB = By.xpath("//div[@class='green-text']");
    public static final By SEPET_NOTU_TEXTBOX = By.xpath("//textarea[@id='giftnotetext']");
    public static final By SEPET_NOTU_TEXTBOX_CSS = By.cssSelector("#giftnotetext");
    public static final By SEPET_HEDIYE_STOK_UYARISI = By.xpath("//input[@value='Tamam']");
    public static final By SEPET_HEDIYE_STOK_UYARISI_MWEB = By.xpath("//button[normalize-space()='Tamam']");
    public static final By SEPET_BOTTOM_HEDIYE_SECIMI_2 = By.xpath("//div[@class='offered-items']/a[2]");
    public static final By SEPET_BOTTOM_HEDIYE_SECIMI_3 = By.xpath("//div[@class='offered-items']/a[3]");
    public static final By SEPET_HEDIYE_SECIM_POPUP_1 = By.xpath("//div[@class='fancybox-overlay fancybox-overlay-fixed']//li[1]");
    public static final By SEPET_HEDIYE_SECIM_POPUP_2 = By.xpath("//div[@class='fancybox-overlay fancybox-overlay-fixed']//li[2]");
    public static final By SEPET_DEVAM_ET_BUTTON_FITMODA = By.xpath("//div[@class='right-side']//input[@id='ContinueOrderButton']");
    public static final By SEPET_DEVAM_ET_BUTTON = By.id("checkout");
    public static final By SEPET_ODEME_ADIMINA_GECMEK_ICIN_ADRES_EKLE_UYARISI = By.xpath("//p[contains(text(),'Ödeme adımına geçmek için teslimat adresinizi ekle')]");
    public static final By SEPET_SIPARISI_TAMAMLA_BUTTON = By.xpath("//input[@id='nextstep']");
    public static final By SIPARIS_ALINDI_SIPARISINIZ_TAMAMLANDI_TEXT = By.xpath("//strong[contains(text(),'Siparişiniz Başarıyla Tamamlandı.')]");
    public static final By SIPARIS_ALINDI_SIPARISINIZ_TAMAMLANDI_TEXT_MWEB = By.xpath("//div[@class='order-completed-page']");
    public static final By SIPARIS_ALINDI_SIPARISINIZ_TAMAMLANDI_TEXT_WEB = By.xpath("//strong[contains(text(),'Siparişiniz Başarıyla Tamamlandı.')]");
    public static final By SIPARIS_ALINDI_ODUL_POPUP_MWEB = By.xpath("//span[@class='notification-title']");
    public static final By SEPET_ODEME_ADIMI_KVKK_CHECKBOX = By.xpath("(//i[@class='sozlesme-check'])[2]");
    public static final By SEPET_ODEME_ADIMI_KVKK_TEXT = By.xpath("//label[contains(text(),'ma ticari elektronik ileti gönderilmesine burada b')]");
    public static final By ADRES_PAGE_DEVAM_ET_BUTTON_ID = By.id("ContinueOrderButton");
    public static final By ADRES_PAGE_DEVAM_ET_BUTTON_ID_WEB = By.id("checkout");
    public static final By ADRES_PAGE_DEVAM_ET_BUTTON_ID_WEB_FITMODA = By.xpath("//div[@class='right-side']//input[@id='ContinueOrderButton']");
    public static final By SATIS_SOZLESMESI_PUPOP = By.xpath("//div[@class='fancybox-outer']");
    public static final By SATIS_SOZLESMESI_CLOSE_BUTTON = By.xpath("//a[@title='Close']");
    public static final By ODEME_PAGE_HAVALE_SECENEK_WEB = By.xpath("//label[@data-name='Havale']");
    public static final By ODEME_PAGE_HAVALE_BUTON_WEB = By.cssSelector("label[data-name='Havale'] p']");
    public static final By ODEME_PAGE_HAVALE_BUTON_WEB2 = By.xpath("(//div[@class='payment-method'])[2]");
    public static final By GUEST_ODEME_HAVALE_SECENEGI = By.xpath("//a[@name='Payments.MoneyTransfer']");
    public static final By GUEST_KREDI_KARTI_SECENEGI = By.xpath("//a[@name='Payments.Inveon']");
    public static final By SIPARIS_ALINDI_PAGE_KAZANILAN_PUAN_FIELD = By.xpath("//tr[@class='earned-points']");
    public static final By SIPARIS_ALINDI_PAGE_KAZANILAN_PUAN_FIELD_WEB = By.xpath("//span[contains(text(),'Kazanılan Puan')]");
    public static final By SIPARIS_ALINDI_KAZANILAN_PUAN_BOTTOM_FIELD = By.xpath("//span[@class='notification-title']");
    public static final By SIPARIS_ALINDI_KAZANILAN_PUAN_TOP_FIELD_WEB = By.xpath("//span[@class='notification-title']");
    public static final By ODEME_SECIMINE_GERI_DON = By.xpath("//a[contains(text(),'ÖDEME SEÇİMİNE GERİ DÖN')]");
    public static final By ODEME_PAGE_KREDI_KARTINI_KAYDET_FIELD = By.xpath("//label[@for='SaveOcpCreditCard']");
    public static final By ODEME_PAGE_KART_3D_SECURE_KULLAN_TEXT = By.xpath("//span[normalize-space()='3D Secure kullan']");
    public static final By ODEME_PAGE_SOZLESME_ONAY_WEB = By.xpath("//div[@class='accpet-terms-wrapper']");
    public static final By ODEME_PAGE_KREDI_KARTI_TAKSIT_SECENEKLERI_TEXT_WEB = By.xpath("//div[@id='installmentscontainer']");
    public static final By ODEME_PAGE_KREDI_KARTI_TAKSIT_SECENEKLERI_FIELD_WEB = By.xpath("//div[@id='installment-table-content-div']");
    public static final By ODEME_PAGE_KAYITLI_KARTLARIM_BUTTON = By.id("savedCardBtn");
    public static final By ODEME_PAGE_HAVALE_BANKA_SECIM = By.xpath("//select[@name='bankList']");
    public static final By ODEME_PAGE_HAVALE_BANKA_SECIM_V2 = By.id("bankListText");
    public static final By ODEME_PAGE_HAVALE_BANKA_SECIM_GARANTI = By.xpath("//option[@value='Garanti Bankası']");
    public static final By ODEME_PAGE_HAVALE_BANKA_SECIM_GARANTI_V2 = By.xpath("//tr[@value='Garanti Bankası']");
    public static final By ODEME_PAGE_HAVALE_BANKA_SECIM_GARANTI_WEB = By.xpath("//option[@value='Garanti Bankası']");
    public static final By ODEME_PAGE_SOZLESME_ONAY_CHECKBOX = By.xpath("//i[@class='sozlesme-check']");
    public static final By ODEME_PAGE_SOZLESME_ONAY_MWEB = By.xpath("//label[@for='accept_terms_1']");
    public static final By SEPET_HEDIYE_SECIM_POPUP_SIZE = By.xpath("//div[@class='voption gift-select popup-option-gift-select']//ul");
    public static final By SEPET_HEDIYE_SECIM_1_SUPPLEMENTLER = By.xpath("/html/body/div[22]/div/div/div/div/div/div[2]/div/div/div/div/div/ul/li[1]");
    public static final By SEPET_HEDIYE_SECIM_1_VITAMINLER = By.xpath("/html/body/div[21]/div/div/div/div/div/div[2]/div/div/div/div/div/ul/li[1]");
    public static final By SEPET_HEDIYE_SECIM_2 = By.xpath("/html/body/div[9]/div/form/div/div[1]/div[3]/div/div/a[2]/label/span");
    public static final By SIPARIS_OZETI_TOPLAM_URUN = By.cssSelector("div[class='showHideProductsBtn'] span");
    public static final By ADRES_PAGE_SIPARIS_OZETI_ICON_SIZE = By.xpath("(//div[@class='summary-quantity'])");
    public static final By ADRES_PAGE_SIPARIS_OZETI_URUN_SIZE = By.xpath("//div[@class='order-summary-small']//li");
    public static final By ADRES_PAGE_SIPARIS_OZETI_ICON_1 = By.xpath("/html/body/div[9]/div/div[3]/div[2]/div[2]/div/div/div[1]/div/ul/li[1]/div[1]/span");
    public static final By ADRES_PAGE_SIPARIS_OZETI_FIELD = By.xpath("//div[@class='showHideProductsBtn']");
 //   public static final By ADRES_PAGE_YENI_ADRES_EKLE_BUTTON_WEB = By.xpath("//a[normalize-space()='Yeni Adres Ekle']");
    public static final By ADRES_PAGE_TESLIMAT_ADRES = By.xpath("//div[@class='selected-address-item selected-shipping AAA has-bg']//h2[1]");
    public static final By ADRES_PAGE_FATURA_ADRES = By.xpath("//div[@class='selected-address-item selected-billing BBB has-bg']//h2[1]");

    public static final By BASKET_NULL_DESCRIPTION =By.xpath("//div[@class='emptyCartMessage']//p[contains(text(),'r.')]");

}