package objectRepository;

import org.openqa.selenium.By;

public class HomePageOR {

    public static final By BOTTOM_DESCRIPTION_TITLE_MWEB = By.xpath("/html/body/div[2]/div[4]/div[9]/h1");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_1_MWEB = By.xpath("/html/body/div[2]/div[4]/div[9]/p[1]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_2_MWEB = By.xpath("/html/body/div[2]/div[4]/div[9]/p[2]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_3_MWEB = By.xpath("/html/body/div[2]/div[4]/div[9]/p[3]");
    public static final By BOTTOM_DEVAMINI_OKU_MWEB = By.xpath("//a[@id='showSeoDetail-btn']");
    public static final By BOTTOM_DESCRIPTION_KAPAT_MWEB = By.id("hideSeoDetail-btn");

    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_4_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[1]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_5_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[2]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_6_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[3]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_7_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[4]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_8_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[5]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_9_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[6]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_10_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[7]");
    public static final By BOTTOM_DESCRIPTION_PARAGRAPH_11_MWEB = By.xpath("//*[@id=\"showSeoDetail\"]/p[8]");
    public static final By BOTTOM_KISISEL_VERILERIN_KORUNMASI_WEB = By.xpath("//a[contains(text(),'KİŞİSEL VERİLERİN KORUNMASI')]");
    public static final By BOTTOM_KISISEL_VERILERIN_KORUNMASI_WEB_FITMODA = By.xpath("(//a[contains(text(),'Kişisel Verilerin Korunması')])[1]");
    public static final By BOTTOM_ILETISIM_MWEB = By.xpath("//a[contains(text(),'İLETİŞİM')]");
    public static final By BOTTOM_ILETISIM_MWEB_FITMODA = By.xpath("//a[@href='/t/iletisim']");
    public static final By ILETISIM_AD_SOYAD_MWEB = By.xpath("//input[@id='FullName']");
    public static final By ILETISIM_EPOSTA_MWEB = By.xpath("//input[@id='Email']");
    public static final By ILETISIM_TELEFON_MWEB = By.xpath("//input[@id='PhoneNumber']");
    public static final By ILETISIM_SIPARIS_NUMARANIZ_MWEB = By.xpath("//input[@id='OrderId']");
    public static final By ILETISIM_KONU_BASLIGI_MWEB = By.xpath("//input[@id='Title']");
    public static final By ILETISIM_MESAJINIZ_MWEB = By.xpath("//textarea[@id='Enquiry']");
    public static final By ILETISIM_KVKK_CHECKBOX_MWEB = By.xpath("//label[@for='KVKKPermission']//span[1]");
    public static final By ILETISIM_GONDER_BUTTON_MWEB = By.xpath("//input[@id='send-email']");
    public static final By ILETISIM_BIZE_ULASIN_MESAJ_TEXT_MWEB = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/div[1]/div[1]/div/p");
    public static final By AYDINLATMA_METNI_TITLE_WEB = By.xpath("//div[contains(@class,'page-large-title')]");
    public static final By AYDINLATMA_METNI_WRAPPER = By.xpath("//div[@class='static-wrapper topic-aydinlatmametni-mobile']");
    public static final By AYDINLATMA_METNI_WRAPPER_FITMODA = By.xpath("//div[@class='static-wrapper topic-aydinlatmametni']");
    public static final By AYDINLATMA_METNI_DIKEY_VITAMIN_TEXT_WEB = By.xpath("(//p[@dir='ltr'])[1]");
    public static final By AYDINLATMA_METNI_UYELIK_SURECLERI_TITLE_WEB = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='static-wrapper topic-aydinlatmametni-mobile']/div[@class='page-content']/p[8]");
    public static final By AYDINLATMA_METNI_UYELIK_SURECLERI_TITLE_WEB_FITMODA = By.xpath("//span[contains(text(),'ÜYELİK SÜREÇLERİ')]");
    public static final By AYDINLATMA_METNI_SIPARIS_IADE_SURECLERI_TITLE_WEB = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='static-wrapper topic-aydinlatmametni-mobile']/div[@class='page-content']/p[11]");
    public static final By AYDINLATMA_METNI_SIPARIS_IADE_SURECLERI_TITLE_WEB_FITMODA = By.xpath("//span[contains(text(),'SİPARİŞ SÜREÇLERİ VE İADE SÜREÇLERİ')]");
    public static final By AYDINLATMA_METNI_MUHASEBE_FINANS_SURECLERI_TITLE_WEB = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='static-wrapper topic-aydinlatmametni-mobile']/div[@class='page-content']/p[16]");
    public static final By AYDINLATMA_METNI_MUHASEBE_FINANS_SURECLERI_TITLE_WEB_FITMODA = By.xpath("//span[contains(text(),'MUHASEBE VE FİNANS SÜREÇLERİ')]");
    public static final By AYDINLATMA_METNI_ILETISIM_SURECLERI_TITLE_WEB = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='static-wrapper topic-aydinlatmametni-mobile']/div[@class='page-content']/p[22]");
    public static final By AYDINLATMA_METNI_ILETISIM_SURECLERI_TITLE_WEB_FITMODA = By.xpath("//span[contains(text(),'İLETİŞİM SÜREÇLERİ')]");
    public static final By AYDINLATMA_METNI_MUSTERI_MEMNUNIYETI_SURECLERI_TITLE_WEB = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='static-wrapper topic-aydinlatmametni-mobile']/div[@class='page-content']/p[28]");
    public static final By AYDINLATMA_METNI_MUSTERI_MEMNUNIYETI_SURECLERI_TITLE_WEB_FITMODA = By.xpath("//span[contains(text(),'MÜŞTERİ MEMNUNİYETİ SÜREÇLERİ')]");
    public static final By AYDINLATMA_METNI_HUKUKI_SURECLER_TITLE_WEB = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='static-wrapper topic-aydinlatmametni-mobile']/div[@class='page-content']/p[36]");
    public static final By AYDINLATMA_METNI_HUKUKI_SURECLER_TITLE_WEB_FITMODA = By.xpath("//span[contains(text(),'HUKUKİ SÜREÇLER')]");
    public static final By AYDINLATMA_METNI_KVKK_EMAIL_TITLE_WEB = By.xpath("//tbody/tr/td/p[@dir='ltr']/a[@href='mailto:kvkk@supplementler.com']/span[1]");
    public static final By HEADER_TITLE_CART = By.xpath("//a[@href='/cart']");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_MWEB = By.id("contactUsMessage");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_ADINIZ_SOYADINIZ_MWEB = By.id("FullName");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_EMAIL_MWEB = By.id("Email");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_KONU_SIPARISIM_HAKKINDA_MWEB = By.xpath("//select[@name='ContactUsSubjectId']");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_TELEFON_MWEB = By.id("PhoneNumber");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_SIPARIS_NUMARANIZ_MWEB = By.id("OrderId");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_KONU_BASLIGI_MWEB = By.id("Title");
    public static final By ILETISIM_PAGE_ILETISIM_FORM_MESAJINIZ_MWEB = By.id("Enquiry");
    public static final By ILETISIM_PAGE_KVKK_CHEKBOX_MWEB = By.cssSelector("label[for='KVKKPermission'] span:nth-child(1)");
    public static final By ILETISIM_PAGE_GONDER_BUTTON_MWEB = By.id("send-email");
    public static final By ILETISIM_PAGE_FORM_GONDERILDI_TEXT = By.xpath("//div[@class='htmlcontent-body']");
    public static final By ILETISIM_PAGE_FORM_GONDERILDI_ANASAYFA_BUTTON = By.xpath("//a[normalize-space()='Ana Sayfa']");
    public static final By TOP_MENU_BUTTON = By.xpath("//span[@class='fa fa-bars']");
    public static final By TOP_MENU_KISISEL_TAVSIYE = By.xpath("//span[contains(text(),'Kişisel Tavsiye')]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_TESTE_BASLA_BUTTON = By.xpath("//a[@class='start-quiz quiz-btn']");
    public static final By TOP_MENU_KISISEL_TAVSIYE_CINSIYET_ERKEK = By.xpath("//a[normalize-space()='ERKEK']");
    public static final By TOP_MENU_KISISEL_TAVSIYE_CINSIYET_KADIN= By.xpath("//a[normalize-space()='KADIN']");
    public static final By TOP_MENU_KISISEL_TAVSIYE_SONRAKI_BUTTON = By.xpath("//a[@class='quiz-next']");
    public static final By TOP_MENU_KATEGORILER = By.xpath("//span[normalize-space()='Kategoriler']");
    public static final By TOP_MENU_KATEGORILER_KOLOJEN = By.xpath("(//span[@class='mlabel'][normalize-space()='Kolajen (Collagen)'])[1]");
    public static final By TOP_MENU_KATEGORILER_KOLOJEN_TIP2 = By.xpath("//a[@class='track-link'][normalize-space()='Tip II Kolajen']");
    public static final By TOP_MENU_KATEGORILER_BALIK_KOLOJENI = By.xpath("//a[@class='track-link'][contains(text(),'Balık (Marine) Kolajeni')]");
    public static final By TOP_MENU_KATEGORILER_HYALURONIK_ASIT = By.xpath("//a[@class='track-link'][normalize-space()='Hyalüronik Asit (Hyaluronic Acid)']");
    public static final By TOP_MENU_KATEGORILER_KOLOJEN_TIP1 = By.xpath("//a[@class='track-link'][normalize-space()='Tip I-III Kolajen']");
    public static final By TOP_MENU_KATEGORILER_ARA_BASLIK_3 = By.xpath("/html/body/div[2]/div[4]/div[2]/ul/li[3]/a/span");
    public static final By TOP_MENU_KISISEL_TAVSIYE_COCUK = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/ul/li[3]/div[2]/div/a");
    public static final By TOP_MENU_KISISEL_TAVSIYE_GENC = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/ul/li[3]/div[3]/div/a");
    public static final By TOP_MENU_KISISEL_TAVSIYE_MEYVE_AZHIC_BUTTON = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/ul/li[5]/div[1]/div/a[1]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_MEYVE_COK_BUTTON = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/ul/li[5]/div[1]/div/a[2]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_ALKOL_AZHIC_BUTTON = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/ul/li[5]/div[2]/div/a[1]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_SIGARA_AZHIC_BUTTON = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/ul/li[5]/div[3]/div/a[1]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_SIGARA_COK_BUTTON = By.xpath("/html/body/div[2]/div[4]/div[2]/div[3]/ul/li[5]/div[3]/div/a[2]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_ENERJI_CHECKBOX = By.xpath("//a[contains(text(),'ENERJİ, YORGUNLUK ve BİTKİNLİK')]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_BAGISIKLIK_CHECKBOX = By.xpath("//a[contains(text(),'BAĞIŞIKLIK SİSTEMİ')]");
    public static final By TOP_MENU_KISISEL_TAVSIYE_URUNLER_GOSTER_BUTTON = By.xpath("//a[@class='show-products quiz-btn']");
    public static final By GENERAL_FIRST_PRODUCT_IN_LIST = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='productlist']/div[1]");
    public static final By GENERAL_SECOND_PRODUCT_IN_LIST = By.xpath("//body/div[@class='wrapper']/div[@class='bodyWrapper']/div[@class='productlist']/div[2]");
    public static final By HOME_PAGE_SEARCH_BAR = By.xpath("//input[@id='TxtSearchBox']");
    public static final By URUN_LISTELEME_ILK_URUN_TITLE_MWEB = By.xpath("(//div[@class='productlist-detail'])[1]");
    public static final By SEPETE_EKLE = By.xpath("//*[@id=\"tabitem1\"]/div/div/div[2]/div/ul/li[1]/div/div[3]/div[2]/div/div");
    public static final By HOME_PAGE_SEARCH_BAR_ARA_BUTTON = By.xpath("//a[@id='search-btn']");

}
