package objectRepository;

import org.openqa.selenium.By;

public class SiparisAlindiOR {
    public static final By SIPARIS_ALINDI_SIPARIS_DETAYI_BUTTON = By.xpath("//a[@id='orderDetail']");
    public static final By SIPARIS_ALINDI_SATIN_ALDIGINIZ_URUNLER_TEXT_WEB = By.xpath("//h4[contains(text(),'Satın Aldığınız Ürünler')]");
    public static final By SIPARIS_ALINDI_SIPARISINIZI_BURADAN_TAKIP_EDEBILIRSINIZ_TEXT = By.xpath("//div[@class='thank-you order-completed-page']");
    public static final By SIPARIS_ALINDI_SIPARISINIZI_BURADAN_TAKIP_EDEBILIRSINIZ_TEXT_WEB = By.xpath("//div[@class='alert alert-primary']");
    public static final By SIPARIS_ALINDI_SIPARISINIZI_BURADAN_TAKIP_EDEBILIRSINIZ_LINK = By.xpath("//a[normalize-space()='buradan']");
    public static final By SIPARIS_ALINDI_PAGE_SIPARIS_NUMARASI=By.xpath("//tr[@class='order-number']//td[4]/strong");
    public static final By SIPARIS_ALINDI_PAGE_SIPARIS_NUMARASI_WEB=By.cssSelector("li[class='order-number'] div strong");
    public static final By SIPARIS_ALINDI_PAGE_HAVALE_SIPARIS_NO_INFO=By.xpath("//div[@class='order-completed-page-remittance-wrapper order-quick-info-div-padding']");
    public static final By SIPARIS_ALINDI_PAGE_HAVALE_SIPARIS_NO_INFO_WEB=By.xpath("//div[@class='info-box']//p[contains(text(),'nda')]");
    public static final By SIPARIS_ALINDI_PAGE_SIPARIS_ODEME_YONTEMI=By.cssSelector("td[class='order-completed-page-payment-method'] strong[class='order-completed-information-values']");
    public static final By SIPARIS_ALINDI_PAGE_SIPARIS_ODEME_YONTEMI_WEB=By.cssSelector("body > div.in_container > div > div.completed-page > div.welcome-space > div.completed-page-content-v2 > div.right-side > div.order-sum > ul > li:nth-child(3) > div:nth-child(3)");
    public static final By SIPARIS_ALINDI_PAGE_SIPARIS_ODEME_YONTEMI_FITMODA=By.cssSelector("td[class='order-completed-page-payment-method'] div[class='order-completed-information-values']");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_FIELD=By.xpath("//div[@class='bank-detail']");
    public static final By SIPARIS_ALINDI_PAGE_HAVALE_ALERT_WEB=By.xpath("//div[@class='alert alert-secondary']");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_IBAN_WEB=By.xpath("(//td)[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_NO_WEB=By.xpath("(//td)[4]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_KODU_WEB=By.xpath("(//td)[8]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_ADI_WEB=By.xpath("(//td)[6]");
    public static final By SIPARIS_ALINDI_PAGE_TESLIMAT_SAATI_WEB=By.xpath("/html/body/div[9]/div/div[1]/div[1]/div[2]/div[2]/div[1]/ul/li[4]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_TESLIMAT_SAATI_WEB_FITMODA=By.xpath("/html/body/div[7]/div[1]/div/div/div[2]/div[2]/div[1]/ul/li[4]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_ADI_WEB=By.xpath("body > div.in_container > div > div.completed-page > div.welcome-space > div.completed-page-content-v2 > div.left-side > div.bank-list-container > div.bank-detail > div.bank-information > div.col-sm-12.col-xs-12.company-bank-account > strong");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_IBAN=By.xpath("(//div)[33]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_IBAN_GUEST=By.xpath("(//div)[30]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_NO=By.xpath("(//div)[37]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_NO_GUEST=By.xpath("(//div)[34]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_KODU=By.xpath("(//div)[40]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_KODU_GUEST=By.xpath("(//div)[37]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_ADI=By.cssSelector("body > div:nth-child(6) > div:nth-child(5) > div:nth-child(3) > div:nth-child(4) > div:nth-child(2) > div:nth-child(3) > strong:nth-child(2)");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_ADI_GUEST=By.cssSelector("body > div:nth-child(6) > div:nth-child(5) > div:nth-child(3) > div:nth-child(3) > div:nth-child(2) > div:nth-child(3) > strong:nth-child(2)");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_ADI_FITMODA=By.cssSelector("body > div:nth-child(6) > div:nth-child(4) > div:nth-child(4) > div:nth-child(4) > div:nth-child(2) > div:nth-child(3) > strong:nth-child(2)");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_ADI_FITMODA_GUEST=By.cssSelector("body > div:nth-child(6) > div:nth-child(4) > div:nth-child(4) > div:nth-child(3) > div:nth-child(2) > div:nth-child(3) > strong:nth-child(2)");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_ADI=By.xpath("//div[@class='bank-detail']//div[4]//strong[1]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_IBAN_VITAMINLER=By.xpath("//body[1]/div[2]/div[4]/div[2]/div[4]/div[2]/div[2]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_IBAN_VITAMINLER_GUEST=By.xpath("(//div)[29]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_IBAN_FITMODA=By.xpath("/html/body/div[2]/div[3]/div[2]/div[4]/div[2]/div[2]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_IBAN_FITMODA_GUEST=By.xpath("(//div)[34]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_NO_VITAMINLER=By.xpath("//body[1]/div[2]/div[4]/div[2]/div[4]/div[2]/div[2]/div[3]/div[1]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_NO_VITAMINLER_GUEST=By.xpath("(//div)[33]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_NO_FITMODA=By.xpath("/html/body/div[2]/div[3]/div[2]/div[4]/div[2]/div[2]/div[3]/div[1]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_HESAP_NO_FITMODA_GUEST=By.xpath("(//div)[38]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_KODU_VITAMINLER=By.xpath("//body[1]/div[2]/div[4]/div[2]/div[4]/div[2]/div[2]/div[3]/div[2]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_KODU_VITAMINLER_GUEST=By.xpath("(//div)[36]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_KODU_FITMODA=By.xpath("/html/body/div[2]/div[3]/div[2]/div[4]/div[2]/div[2]/div[3]/div[2]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_BANKA_BILGILERI_SUBE_KODU_FITMODA_GUEST=By.xpath("(//div)[41]");
    public static final By SIPARIS_ALINDI_PAGE_URUNLER_FIELD=By.xpath("//ul[@class='order-items']");
    public static final By SIPARIS_ALINDI_PAGE_URUNLER_1_ITEM=By.xpath("//div[@class='order-complete']//li[1]");
    public static final By SIPARIS_ALINDI_PAGE_URUNLER_1_ITEM_WEB=By.xpath("/html/body/div[9]/div/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]");
    public static final By SIPARIS_ALINDI_PAGE_URUNLER_1_ITEM_WEB_FITMODA=By.xpath("//div[@class=' cart-items-row']");
    public static final By SIPARIS_ALINDI_PAGE_URUNLER_FIELD_WEB=By.xpath("//div[@class='completed-cart-items-v2']");
    public static final By SIPARIS_ALINDI_PAGE_ADRES_2_FIELD=By.xpath("(//div[@class='completed-address'])[2]");
    public static final By SIPARIS_ALINDI_PAGE_ADRES_2_FIELD_WEB=By.xpath("/html/body/div[9]/div/div[1]/div[1]/div[2]/div[2]/div[2]/div/div");
    public static final By SIPARIS_ALINDI_PAGE_ADRES_2_FIELD_WEB_FITMODA=By.xpath("/html/body/div[7]/div[1]/div/div/div[2]/div[2]/div[2]/div/div");
    public static final By SIPARISLARIM_PAGE_BACK_BUTTON=By.xpath("//a[contains(text(),'SİPARİŞLERİM')]");
    public static final By SIPARISLARIM_PAGE_BACK_BUTTON_WEB=By.xpath("//span[@class='crumb-active']");
    public static final By SIPARISLERIM_PAGE_SIPARISIMI_IPTAL_ET_WEB=By.xpath("//a[@id='returnitems']");
    public static final By SIPARISLERIM_PAGE_SIPARISIMI_IPTAL_ET_SIPARISI_IPTAL_ET_WEB=By.id("btnCancelOrder");
    public static final By SIPARISLERIM_PAGE_SIPARISINIZ_IPTAL_EDILDI_WEB=By.xpath("//div[@id='orderUpdateWindowResult']");
    public static final By SIPARISLERIM_PAGE_SIPARISIMI_IPTAL_ET_MESAJ_WEB=By.xpath("//textarea[@placeholder='Mesajınız Bu Bölümde...']");
    public static final By SIPARISLERIM_PAGE_SIPARISIMI_IPTAL_ET_DIGER_WEB=By.xpath("//li[8]//label[1]");
    public static final By SIPARIS_ALINDI_PAGE_GUEST_SIPARISINIZ_TAMAMLANDI_TEXT_MWEB = By.xpath("//h1[contains(text(),'SİPARİŞİNİZ TAMAMLANDI')]");
}
